on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: yettoapp/actions/setup-languages@main
        with:
          node: true

      - name: Build Package
        run: npm run build

      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(cat package.json | jq .version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Compile New Version
        run: |
          RELEASE_VERSION=$(npx semver $CURRENT_VERSION -i github.event.inputs.releaseType)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Bump to $RELEASE_VERSION"

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"

      - name: Create tag
        run: |
          git log -1 --stat
          npm version $RELEASE_VERSION
          git tag -a v$RELEASE_VERSION -m "Release v$RELEASE_VERSION"
          git push origin main --tags

      - name: Create changelog for release
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.GH_VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./multi-format-*"
          tag: ${{ env.GIT_TAG }}
          body: ${{ steps.github_release.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha')}}
